// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bybqxpgetjspkbaoyitr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJ5YnF4cGdldGpzcGtiYW95aXRyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzg5NDI0OTYsImV4cCI6MjA1NDUxODQ5Nn0.BxRUk3uc3rB_ggnmPr8XzAqVDHhBs8N3rovGoQBfFeE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);